SRCS=$(wildcard *.c) unicode.c
ASRC=$(wildcard *.S)

VPATH=option
# Include the standard makefile for the embedded systems 1 & 2 labs 
EXTRA_CFLAGS=-Wno-unused-function -I../drivers -I../interrupt
include $(LMIBASE)/bbb/make/bbb_lib.mk


