SRCS=$(wildcard *.c)
ASRC=$(wildcard *.S)

# Include the standard makefile for the embedded systems 1 & 2 labs 
VPATH=
EXTRA_CFLAGS=-I../ff12b -I../mmu -I../interrupt -I../syscall -I../system -I../file_system -I../shell -I../devices

include $(LMIBASE)/bbb/make/bbb_lib.mk