SRCS=$(wildcard *.c)
ASRC=$(wildcard *.S)

LIBDIRS=../utils

# Include the standard makefile for the embedded systems 1 & 2 labs 
VPATH=
EXTRA_CFLAGS=-I../ff12b -I../devices -I../drivers

include $(LMIBASE)/bbb/make/bbb_lib.mk