SRCS=$(wildcard *.c) 
ASRC=$(wildcard *.S)

CFLAGS+=-I../interrupts -DINTC_EN=1

# Include the standard makefile for the embedded systems 1 & 2 labs 
##EXTRA_CFLAGS=-Wno-unused-parameter
include $(LMIBASE)/bbb/make/bbb_lib.mk